version: '3.7'

services:
  rsactfd:
    build: .
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UPLOAD_FOLDER=/opt/uploads
      - DATABASE_URL=mysql+pymysql://root:ctfd@rsadb/ctfd
      - REDIS_URL=redis://rsacache:6379
      - WORKERS=1
      - LOG_FOLDER=/opt/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - PORT=8000
      - IMPORT_ID=RSA2020
    depends_on:
      - rsadb
    networks:
        default:
        internal:

  rsadb:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - type: volume
        source: rsactfd
        target: /data
    networks:
        internal:
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  rsacache:
    image: redis:4
    restart: always
    volumes:
    - type: volume
      source: rsactfd
      target: /data
    networks:
        internal:

volumes:
    rsactfd:

networks:
    default:
    internal:
        internal: true
